<a href="https://colab.research.google.com/github/greeanday/newrepo/blob/master/subject1_Q4_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Q4.
Calculate the energy, Shannon entropy, maximum (amplitude and location),
minimum (amplitude and location) for this magnitude signal.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataFrame=pd.read_csv("subject101.dat",sep=" ",header=None)
dataFrame.shape[1]

dataFrame.columns=["timestamp","activityID","heart_rate"]+[f'col_{i}' for i in range(4,55)]

dataFrame["col_40"]=pd.to_numeric(dataFrame["col_40"], errors="coerce")
dataFrame["col_41"]=pd.to_numeric(dataFrame["col_41"], errors="coerce")
dataFrame["col_42"]=pd.to_numeric(dataFrame["col_42"], errors="coerce")

walking=dataFrame[dataFrame["activityID"]==4]
xyz = walking[["timestamp","col_40", "col_41", "col_42"]].dropna()

magnitude = np.sqrt(xyz["col_40"]**2 + xyz["col_41"]**2 + xyz["col_42"]**2)
print(magnitude)
print(xyz.iloc[1]["timestamp"])


223759    9.835221
223760    9.869890
223761    9.883564
223762    9.829694
223763    9.834589
            ...   
246007    9.861381
246008    9.837874
246009    9.833071
246010    9.877807
246011    9.863739
Length: 22185, dtype: float64
2245.98


In [ ]:
max_value = np.max(magnitude)
print(max_value)
max_index = np.argmax(magnitude)
print(max_index)
max_value_time= xyz.iloc[max_index]["timestamp"]
print(max_value_time)

print(xyz.iloc[max_index])

print(f"Maximum Amplitude: {max_value} \nMax Amplitude Location Index: {max_index} \nMax Amplitude Time (second): {max_value_time} ")


156.44553695855308
17160
2418.13
timestamp    2418.1300
col_40       -155.3560
col_41         -9.6815
col_42         15.6840
Name: 240975, dtype: float64
Maximum Amplitude: 156.44553695855308 
Max Amplitude Location Index: 17160 
Max Amplitude Time (second): 2418.13 


In [ ]:
min_value=np.min(magnitude)
print(min_value)
min_index=np.argmin(magnitude)
print(min_index)
min_value_time=xyz.iloc[min_index]["timestamp"]
print(min_value_time)
print(xyz.iloc[min_index])

print(f"Minimum Amplitude: {min_value} \nMin Amplitude Location Index: {min_index} \nMin Amplitude Time (second): {min_value_time} ")

2.0078757240636285
18438
2430.94
timestamp    2430.940000
col_40         -0.039880
col_41         -0.615606
col_42          1.910760
Name: 242256, dtype: float64
Minimum Amplitude: 2.0078757240636285 
Min Amplitude Location Index: 18438 
Min Amplitude Time (second): 2430.94 


In [ ]:
print(magnitude)
print(magnitude.shape)
print(magnitude.iloc[2])

NameError: name 'magnitude' is not defined

In [ ]:
energy=0
for i in range(len(magnitude)):
  energy+=magnitude.iloc[i]**2

print(f"energy: {energy}")

#YA DA DİREK HESAPLAMAK İÇİN:

energy_altarnatif_hesaplama=np.sum(magnitude**2)
print(energy_altarnatif_hesaplama)

print(f"energy: {energy_altarnatif_hesaplama}")

energy: 7817781.791419155
7817781.791419092
energy: 7817781.791419092


In [ ]:
print(len(magnitude))

22185


# **SHANNON ENTROPY HESAPLLAMA**
ÖNCE Freedman–Diaconis bin sayısı hesaplayacağım. Bu istatiksel olarak daha anlamlı ve doğru entropy sonucu almanı sağlıyor. bin sayısı demek veri setimi toplam kaça böldüğüm demek oluyor. veri setini veri sayısına göre değil de örneğin 100 parçaya bölüp bu 100 parçanın ağırlıklı olasılık hesaplaması üzerinden entropi hesabu yapıyoruz. eğer veri sayısına göre yapsak çok yüksek entropi çıkabilirmiş. ama doğru olan da o gibi de geliyor? diyelim 2 grubum var biri kontrol, bu durumda ikisinin de veri uzunluğuaynıysa ortak bir rakamda da yapabiliriz sanırım doğru olması içn ? veya eğer ikisinin data uzunlukları farklı ise ikisi için ayrı ayrı Freedman–Diaconis bin sayısı heaapalyıp farklı bin sayılaır ile mi yapmak daha doğru olur, yoksa aynı bin sayısı mı olmalı? ya farklı bin sayıları olursa daha yanlış olursa?



In [ ]:
import numpy as np
from scipy.stats import entropy, iqr
#IQR (interquartile Range) hesaplama
data_iqr=iqr(magnitude)

#bin genişliği hesapla
bin_width=data_iqr/(len(magnitude)**(1/3))

#bin sayısını hesapla
bin_count=int(np.ceil((magnitude.max()- magnitude.min()) / bin_width))

#histogram hesapla
counts, _ =np.histogram(magnitude, bins=bin_count, density=True)

#olasılıklar ve entropi hesapla
probabilities= counts/np.sum(counts)
H=entropy(probabilities, base=2)


print(f"Freedman–Diaconis bin sayısı: {bin_count}")
print(f"Shannon Entropi: {H:.4f} bit")

Freedman–Diaconis bin sayısı: 442
Shannon Entropi: 5.9984 bit


In [ ]:
#veya direk her bir değere göre baksın istersem, ve binler ayırmazsam bu şekilde olur (bu direk orjinal probabilities'i gösterir data setindeki herbir nnktayı kullanır ancak floatlar için değil de daha integer ilerleyen heart rate gibi data seti 1, 23, .. gibi tam sayılardan oluşan gruplarda ve her bi rsayının tek kez temsil edilme ihtimali olmayan sayılarda daha manyıklı. yoksa- aksi taktirde float vs olan bir grupta- binlere ayır ki ağırlıklı ortalamaya göre bakabil entropiye):
sayim = magnitude.value_counts()
print(sayim)
probability_denemesi=sayim/sayim.sum()
H=entropy(probability_denemesi, base=2)
print(f"Shannon Entropi: {H:.4f} bit")

9.863739    1
9.835221    1
9.869890    1
9.883564    1
9.829694    1
           ..
9.820361    1
9.859151    1
9.884593    1
9.879593    1
9.860458    1
Name: count, Length: 22185, dtype: int64
Shannon Entropi: 14.4373 bit


# **Q5**
Divide this magnitude signal into 4-second long segments. Store the segments
as a matrix where each row corresponds to one window.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataFrame=pd.read_csv("subject101.dat",sep=" ",header=None)

dataFrame.shape[1]

dataFrame.columns=["timestamp","activityID","heart_rate"]+[f'col_{i}' for i in range(4,55)]

dataFrame["col_40"]=pd.to_numeric(dataFrame["col_40"], errors="coerce")
dataFrame["col_41"]=pd.to_numeric(dataFrame["col_41"], errors="coerce")
dataFrame["col_42"]=pd.to_numeric(dataFrame["col_42"], errors="coerce")

walking=dataFrame[dataFrame["activityID"]==4]
xyz = walking[["timestamp","col_40", "col_41", "col_42"]].dropna()

magnitude = np.sqrt(xyz["col_40"]**2 + xyz["col_41"]**2 + xyz["col_42"]**2)



önce bir dataframe tasarlayıp sonr onu np.array ile matrixe çevireceğim. Burada önemli olan şeylerden biri, magnitude verisinin uzunluğu 4 ün tam katı değil, son satırda 3 tane NaN kalıyor. son satırı elle en son giriyorum. önce for  döngümde kullanacağım indexleri hesaplamalıım. 4'e bölecek şekilde yapacağım için son satur hariç [0,4,8, ...] şeklinde gidecek bir index listesi oluşturuyorum. sonra for döngümde aslında yeni df'imin her bir satırına magnitude'un 4 er berisinimekliyorum. Sonra en son satırı elle ekliyorum. son satırın eksik 3 column'unu Nan OLARAK (np.nan) giriyorum. ***DİKKAT:*** np.mean(matrix) gibi işlemler NaN döner
Bunun yerine np.nanmean(matrix) gibi fonksiyonlar kullan (İLERİSİ İÇİN) en sonda da len(magnitude) değerimnin dörde bölününceki tamsayı kısmını görüyorum. bunun virgül sonraki kısmı aslında 0.25 yani 4/0.25=1 yani son satıra sadece 1 rakam kalıyor magnitude verisinden demek. o yüzden tam sayı kısmı+1 (rakam,nNAN,NAN,NAN satırı) ile benim yeni matrisimin büyüklüğü uyuşuyor mu diye bakıyorum (matrix.shape) ve aynı olması ben doğruluyıor.

In [ ]:
matrix_4sec_in_a_row=pd.DataFrame(columns=['v1', 'v2', 'v3', 'v4'])
index_base=list(range(int((len(magnitude)-1)/4)))
index=[x*4 for x in index_base]

a=0
for i in index:
  matrix_4sec_in_a_row.loc[a]=[magnitude.iloc[i], magnitude.iloc[i+1], magnitude.iloc[i+2], magnitude.iloc[i+3]]
  a+=1

matrix_4sec_in_a_row.loc[a]=[magnitude.iloc[-1],np.nan,np.nan,np.nan]

matrix=matrix_4sec_in_a_row.to_numpy()
print(matrix.shape)
print(matrix)

len(magnitude)/4

(5547, 4)
[[9.8352214  9.86989005 9.88356388 9.82969423]
 [9.83458903 9.86897603 9.8483943  9.84258651]
 [9.84794184 9.86045832 9.87959316 9.88459272]
 ...
 [9.83152792 9.84374188 9.87652808 9.88445494]
 [9.86138098 9.83787401 9.83307142 9.87780693]
 [9.86373938        nan        nan        nan]]


5546.25

In [ ]:
print(dataFrame.iloc[len(magnitude)])

timestamp     230.230000
activityID      1.000000
heart_rate           NaN
col_4          31.625000
col_5           7.289220
col_6           1.264300
col_7           6.302990
col_8           7.286820
col_9           1.269170
col_10          6.627870
col_11         -0.033948
col_12          0.017288
col_13         -0.030565
col_14         -3.193610
col_15         23.865300
col_16        -54.838800
col_17          1.000000
col_18          0.000000
col_19          0.000000
col_20          0.000000
col_21         33.375000
col_22          0.544619
col_23         -0.065057
col_24          9.616450
col_25          0.360040
col_26         -0.056062
col_27          9.831310
col_28         -0.012943
col_29          0.006072
col_30          0.004826
col_31         46.561800
col_32         12.700100
col_33        -45.528800
col_34          1.000000
col_35          0.000000
col_36          0.000000
col_37          0.000000
col_38         32.000000
col_39          0.182681
col_40         -7.271270


# **2.yol**
Şimdid e df değil de direk liste olarak raw ları oluşturup onu raw datasına çevirmeyi göstercem

In [ ]:
rows = []
for i in index:
    rows.append([magnitude.iloc[i], magnitude.iloc[i+1], magnitude.iloc[i+2], magnitude.iloc[i+3]])
rows.append([magnitude.iloc[-1], np.nan, np.nan, np.nan])
matrix_ikinci_yol=np.array(rows)
print(matrix_ikinci_yol)
print(matrix_ikinci_yol.shape)
print(type(matrix_ikinci_yol))



[[9.8352214  9.86989005 9.88356388 9.82969423]
 [9.83458903 9.86897603 9.8483943  9.84258651]
 [9.84794184 9.86045832 9.87959316 9.88459272]
 ...
 [9.83152792 9.84374188 9.87652808 9.88445494]
 [9.86138098 9.83787401 9.83307142 9.87780693]
 [9.86373938        nan        nan        nan]]
(5547, 4)
<class 'numpy.ndarray'>


# **3. yol**


In [ ]:
import numpy as np

rows = []
for i in range(0, len(magnitude), 4):
    block = [magnitude.iloc[i + j] if i + j < len(magnitude) else np.nan for j in range(4)]
    rows.append(block)

matrix_üçüncü_yol = np.array(rows)
print(matrix_üçüncü_yol)
print(matrix_üçüncü_yol.shape)

[[9.8352214  9.86989005 9.88356388 9.82969423]
 [9.83458903 9.86897603 9.8483943  9.84258651]
 [9.84794184 9.86045832 9.87959316 9.88459272]
 ...
 [9.83152792 9.84374188 9.87652808 9.88445494]
 [9.86138098 9.83787401 9.83307142 9.87780693]
 [9.86373938        nan        nan        nan]]
(5547, 4)


# **BİR ANLAM KARIŞIKLIĞI OLMUŞ. **
SAMPLE HZ0100 OLDUĞIU İÇİN HER BİR İNDEXTE 0.01 SN GEÇİYOR. AMA HOCA 4 SN İSTEMİŞ --> 400 SAMPLE ALMAM GEREK. DOĞRUSU

In [ ]:
rows = []
sampling_rate = 100  # Hz
segment_length = 4 * sampling_rate  # 4 saniye = 400 örnek

for i in range(0, len(magnitude), segment_length):
    segment = magnitude.iloc[i:i+segment_length].values  # .iloc kullandık
    if len(segment) < segment_length:
        segment = np.pad(segment, (0, segment_length - len(segment)), constant_values=np.nan)
    rows.append(segment)

matrix_4sec_segments = np.array(rows)

In [ ]:
print(matrix_4sec_segments)
print(type(matrix_4sec_segments))
print(matrix_4sec_segments.shape)

[[ 9.8352214   9.86989005  9.88356388 ...  9.85272037  9.83379003
   9.82022517]
 [ 9.90059972  9.88599863  9.8789265  ... 15.3508687  15.34657712
  16.98942897]
 [19.60082743 19.73993113 21.07213153 ... 31.99705386 30.11996972
  26.1542025 ]
 ...
 [11.24691497 11.69079851 12.15887657 ...  9.74594703  9.76381555
   9.73711618]
 [ 9.89155688  9.88812266  9.86349498 ...  9.87990752  9.86461121
   9.85364909]
 [ 9.86270113  9.80651563  9.8746304  ...         nan         nan
          nan]]
<class 'numpy.ndarray'>
(56, 400)


# **İLK YAPTIĞIM YOLUMLA-DOĞRU 4SEC. PENCERELİ MATRİX**

In [ ]:
matrix_4sec_new=pd.DataFrame(columns=[f'v{i+1}' for i in range(400)])
index_base=list(range(int((len(magnitude)-1)/400+1)))
index=[x*400 for x in index_base]

a=0
for i in index:

  if i + 400 <= len(magnitude):
    segment = magnitude.iloc[i:i+400].tolist()
  else:
    segment = magnitude.iloc[i:].tolist()
    segment += [np.nan] * (400 - len(segment))

  matrix_4sec_new.loc[a] = segment
  a += 1
matrix=matrix_4sec_new.to_numpy()
print(matrix.shape)
print(matrix)





len(magnitude)/400

(56, 400)
[[ 9.8352214   9.86989005  9.88356388 ...  9.85272037  9.83379003
   9.82022517]
 [ 9.90059972  9.88599863  9.8789265  ... 15.3508687  15.34657712
  16.98942897]
 [19.60082743 19.73993113 21.07213153 ... 31.99705386 30.11996972
  26.1542025 ]
 ...
 [11.24691497 11.69079851 12.15887657 ...  9.74594703  9.76381555
   9.73711618]
 [ 9.89155688  9.88812266  9.86349498 ...  9.87990752  9.86461121
   9.85364909]
 [ 9.86270113  9.80651563  9.8746304  ...         nan         nan
          nan]]


55.4625